import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MemberSummary } from '@/types';

const formatTaka = (amount: number) => {
  const absAmount = Math.abs(amount);
  if (absAmount === 0) return '0 Tk';
  return `${Math.round(absAmount)} Tk`;
};

interface MonthlyStats {
  totalMeals: number;
  totalExpenses: number;
  totalExtraExpenses: number;
  totalDeposits: number;
  totalMaidPayments: number;
  mealRate: number;
}

export const generateTotalReportPDF = (
  monthlyStats: MonthlyStats,
  summaries: MemberSummary[],
  totalPositiveBalance: number,
  totalNegativeBalance: number
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Mess Report - Total Summary', pageWidth / 2, 20, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });
  
  // Summary Section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Summary', 14, 40);
  
  const totalBalance = monthlyStats.totalDeposits - monthlyStats.totalExpenses - monthlyStats.totalExtraExpenses - monthlyStats.totalMaidPayments;
  
  autoTable(doc, {
    startY: 45,
    head: [['Item', 'Amount']],
    body: [
      ['Total Meals (Meel)', monthlyStats.totalMeals.toFixed(1)],
      ['Market Expenses (Bazar)', formatTaka(monthlyStats.totalExpenses)],
      ['Extra Expenses', formatTaka(monthlyStats.totalExtraExpenses)],
      ['Maid Payment (Buya)', formatTaka(monthlyStats.totalMaidPayments)],
      ['Total Deposits', formatTaka(monthlyStats.totalDeposits)],
      ['Cash Balance', `${totalBalance >= 0 ? '+' : '-'}${formatTaka(totalBalance)}`],
      ['Meal Rate', `${formatTaka(monthlyStats.mealRate)} / meal`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
  });
  
  // Balance Summary
  const currentY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Balance Summary', 14, currentY);
  
  autoTable(doc, {
    startY: currentY + 5,
    head: [['Type', 'Amount']],
    body: [
      ['Total Receivable (Paona)', formatTaka(totalPositiveBalance)],
      ['Total Payable (Baki)', formatTaka(totalNegativeBalance)],
    ],
    theme: 'striped',
    headStyles: { fillColor: [34, 197, 94] },
  });
  
  // Member Details
  const memberY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Member-wise Details', 14, memberY);
  
  autoTable(doc, {
    startY: memberY + 5,
    head: [['Name', 'Meals', 'Cost', 'Deposit', 'Balance', 'Status']],
    body: summaries.map(s => [
      s.name,
      s.totalMeals.toFixed(1),
      formatTaka(s.totalCost),
      formatTaka(s.totalDeposit),
      `${s.balance >= 0 ? '+' : ''}${formatTaka(s.balance)}`,
      s.balance > 0 ? 'Pabe' : s.balance < 0 ? 'Debe' : 'Soman',
    ]),
    theme: 'striped',
    headStyles: { fillColor: [139, 92, 246] },
  });
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Mess Manager App', pageWidth / 2, footerY, { align: 'center' });
  
  doc.save('mess-total-report.pdf');
};

export const generateMemberReportPDF = (
  member: MemberSummary,
  monthlyStats: MonthlyStats
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`Individual Report - ${member.name}`, pageWidth / 2, 20, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });
  
  // Member Details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Meal Details', 14, 40);
  
  autoTable(doc, {
    startY: 45,
    head: [['Item', 'Count/Amount']],
    body: [
      ['Total Lunch', member.totalLunch.toString()],
      ['Total Dinner', member.totalDinner.toString()],
      ['Total Meals', member.totalMeals.toFixed(1)],
      ['Meal Rate', `${formatTaka(monthlyStats.mealRate)} / meal`],
    ],
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246] },
  });
  
  // Financial Details
  const finY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Details', 14, finY);
  
  autoTable(doc, {
    startY: finY + 5,
    head: [['Item', 'Amount']],
    body: [
      ['Total Cost', formatTaka(member.totalCost)],
      ['Total Deposit', formatTaka(member.totalDeposit)],
      ['Balance', `${member.balance >= 0 ? '+' : ''}${formatTaka(member.balance)}`],
      ['Status', member.balance > 0 ? 'Will Receive (Pabe)' : member.balance < 0 ? 'Will Pay (Debe)' : 'Settled (Soman)'],
    ],
    theme: 'striped',
    headStyles: { fillColor: member.balance >= 0 ? [34, 197, 94] : [239, 68, 68] },
  });
  
  // Summary Box
  const sumY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(member.balance >= 0 ? 220 : 254, member.balance >= 0 ? 252 : 226, member.balance >= 0 ? 231 : 226);
  doc.rect(14, sumY, pageWidth - 28, 25, 'F');
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(member.balance >= 0 ? 22 : 185, member.balance >= 0 ? 163 : 28, member.balance >= 0 ? 74 : 28);
  
  const statusText = member.balance > 0 
    ? `${member.name} will receive ${formatTaka(member.balance)}`
    : member.balance < 0 
      ? `${member.name} needs to pay ${formatTaka(member.balance)}`
      : `${member.name}'s account is settled`;
  
  doc.text(statusText, pageWidth / 2, sumY + 15, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Mess Manager App', pageWidth / 2, footerY, { align: 'center' });
  
  const safeName = member.name.replace(/\s+/g, '-');
  doc.save(`mess-report-${safeName}.pdf`);
};
